### ISSUE TITLE
Error pushing new update (rich text fields) to dokku

### ISSUE THREAD

**Issue by marykatefain** [liberationphilly/liberationphilly#44]
```
       !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
       
       $ heroku config:set DISABLE_COLLECTSTATIC=1
       
       https://devcenter.heroku.com/articles/django-assets
To dokku@liberationphilly.org:website
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@liberationphilly.org:website'

```

**Comment by marykatefain** [comment]
```
mk@babyshark:~/Projects/liberationphilly$ git push dokku masterCounting objects: 1635, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1546/1546), done.
Writing objects: 100% (1635/1635), 6.39 MiB | 702.00 KiB/s, done.
Total 1635 (delta 182), reused 0 (delta 0)
remote: Resolving deltas: 100% (182/182), completed with 9 local objects.
remote: Preparing /tmp/dokku_git.0fvQ (identifier dokku_git.0fvQ)
-----> Cleaning up...
-----> Building website from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Python app detected
-----> Installing requirements with pip
       Obtaining wagtail-modelchooser from git+https://github.com/candlewaster/wagtailmodelchooser.git@wagtail2#egg=wagtail-modelchooser (from -r /tmp/build/requirements.txt (line 7))
       Cloning https://github.com/candlewaster/wagtailmodelchooser.git (to wagtail2) to /app/.heroku/src/wagtail-modelchooser
       Installing collected packages: wagtail-modelchooser
       Found existing installation: wagtail-modelchooser 0.3.1
       Running setup.py develop for wagtail-modelchooser
       Successfully installed wagtail-modelchooser
       
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
       File "manage.py", line 15, in <module>
       execute_from_command_line(sys.argv)
       File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
       utility.execute()
       File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
       django.setup()
       File "/app/.heroku/python/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
       apps.populate(settings.INSTALLED_APPS)
       File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
       app_config = AppConfig.create(entry)
       File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
       module = import_module(entry)
       File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
       return _bootstrap._gcd_import(name[level:], package, level)
       File "<frozen importlib._bootstrap>", line 978, in _gcd_import
       File "<frozen importlib._bootstrap>", line 961, in _find_and_load
       File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
       ModuleNotFoundError: No module named 'ckeditor'
```

**Comment by marykatefain** [comment]
ty!
