### ISSUE TITLE
500 on /admin/events/event/*/delete/

### ISSUE THREAD

**Issue by alexgleason** [liberationphilly/liberationphilly#47]
```
2018-05-17T22:36:30.719019449Z app[web.1]: Internal Server Error: /admin/events/event/25/delete/
2018-05-17T22:36:30.719069178Z app[web.1]: Traceback (most recent call last):
2018-05-17T22:36:30.719091058Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
2018-05-17T22:36:30.719095392Z app[web.1]:     return self.cursor.execute(sql, params)
2018-05-17T22:36:30.719109147Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
2018-05-17T22:36:30.719113037Z app[web.1]:     return Database.Cursor.execute(self, query, params)
2018-05-17T22:36:30.719116203Z app[web.1]: sqlite3.OperationalError: no such table: main.core_tag
2018-05-17T22:36:30.719119250Z app[web.1]: 
2018-05-17T22:36:30.719122327Z app[web.1]: The above exception was the direct cause of the following exception:
2018-05-17T22:36:30.719125453Z app[web.1]: 
2018-05-17T22:36:30.719128348Z app[web.1]: Traceback (most recent call last):
2018-05-17T22:36:30.719131321Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
2018-05-17T22:36:30.719134589Z app[web.1]:     response = get_response(request)
2018-05-17T22:36:30.719137512Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
2018-05-17T22:36:30.719140684Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2018-05-17T22:36:30.719144188Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
2018-05-17T22:36:30.719147532Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-05-17T22:36:30.719150570Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 574, in wrapper
2018-05-17T22:36:30.719153736Z app[web.1]:     return self.admin_site.admin_view(view)(*args, **kwargs)
2018-05-17T22:36:30.719156738Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
2018-05-17T22:36:30.719159998Z app[web.1]:     response = view_func(request, *args, **kwargs)
2018-05-17T22:36:30.719162895Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
2018-05-17T22:36:30.719166046Z app[web.1]:     response = view_func(request, *args, **kwargs)
2018-05-17T22:36:30.719168946Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
2018-05-17T22:36:30.719172232Z app[web.1]:     return view(request, *args, **kwargs)
2018-05-17T22:36:30.719175165Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
2018-05-17T22:36:30.719186301Z app[web.1]:     return bound_func(*args, **kwargs)
2018-05-17T22:36:30.719189221Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
2018-05-17T22:36:30.719193586Z app[web.1]:     response = view_func(request, *args, **kwargs)
2018-05-17T22:36:30.719196625Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
2018-05-17T22:36:30.719212105Z app[web.1]:     return func.__get__(self, type(self))(*args2, **kwargs2)
2018-05-17T22:36:30.719215453Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1713, in delete_view
2018-05-17T22:36:30.719218953Z app[web.1]:     return self._delete_view(request, object_id, extra_context)
2018-05-17T22:36:30.719221883Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1746, in _delete_view
2018-05-17T22:36:30.719225069Z app[web.1]:     self.delete_model(request, obj)
2018-05-17T22:36:30.719227940Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1032, in delete_model
2018-05-17T22:36:30.719231238Z app[web.1]:     obj.delete()
2018-05-17T22:36:30.719234146Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 891, in delete
2018-05-17T22:36:30.719237317Z app[web.1]:     return collector.delete()
2018-05-17T22:36:30.719240232Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/deletion.py", line 283, in delete
2018-05-17T22:36:30.719243386Z app[web.1]:     count = qs._raw_delete(using=self.using)
2018-05-17T22:36:30.719246311Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 676, in _raw_delete
2018-05-17T22:36:30.719249577Z app[web.1]:     return sql.DeleteQuery(self.model).delete_qs(self, using)
2018-05-17T22:36:30.719260703Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
2018-05-17T22:36:30.719264137Z app[web.1]:     cursor = self.get_compiler(using).execute_sql(CURSOR)
2018-05-17T22:36:30.719267144Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
2018-05-17T22:36:30.719270414Z app[web.1]:     cursor.execute(sql, params)
2018-05-17T22:36:30.719273541Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
2018-05-17T22:36:30.719276723Z app[web.1]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2018-05-17T22:36:30.719279820Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
2018-05-17T22:36:30.719283181Z app[web.1]:     return executor(sql, params, many, context)
2018-05-17T22:36:30.719286113Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
2018-05-17T22:36:30.719289307Z app[web.1]:     return self.cursor.execute(sql, params)
2018-05-17T22:36:30.719292299Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
2018-05-17T22:36:30.719296161Z app[web.1]:     raise dj_exc_value.with_traceback(traceback) from exc_value
2018-05-17T22:36:30.719299223Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
2018-05-17T22:36:30.719304345Z app[web.1]:     return self.cursor.execute(sql, params)
2018-05-17T22:36:30.719309125Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
2018-05-17T22:36:30.719319795Z app[web.1]:     return Database.Cursor.execute(self, query, params)
2018-05-17T22:36:30.719325034Z app[web.1]: django.db.utils.OperationalError: no such table: main.core_tag
```

**Comment by alexgleason** [comment]
The database was corrupted. I don't understand how sqlite works so I had to search it inside a fucking hex editor and was able to figure out what I needed to change.

Shouldn't happen again. It was caused by manually editing the DB in the first place.
